const SET_USERNAME = "SET_USERNAME";

// Weather
const WEATHER_API_REQUESTED = "WEATHER_API_REQUESTED";
const WEATHER_API_RECEIVED = "WEATHER_API_RECEIVED";
const WEATHER_API_FAILED = "WEATHER_API_FAILED";

export {
  SET_USERNAME,
  WEATHER_API_FAILED,
  WEATHER_API_RECEIVED,
  WEATHER_API_REQUESTED,
};
